name: Monthly issue metrics
on:
  workflow_dispatch:
  schedule:
    - cron: '3 2 1 * *'

permissions:
  issues: write
  pull-requests: read

jobs:
  build:
    name: developer q/a metrics
    runs-on: ubuntu-latest

    steps:

    - name: Get dates for last month
      shell: bash
      run: |
        # Calculate the first day of the previous month
        # first_day=$(date -d "last month" +%Y-%m-01)

        # Calculate the last day of the previous month
        # last_day=$(date -d "$first_day +1 month -1 day" +%Y-%m-%d)

        first_day=$(date -d "this month" +2023-09-01)
        last_day=$(date -d "$first_day +1 month -1 day" +%Y-%m-%d)
        
        #Set an environment variable with the date range
        echo "$first_day..$last_day"
        echo "last_month=$first_day..$last_day" >> "$GITHUB_ENV"

    - name: Run issue-metrics tool
      uses: github/issue-metrics@v2.11.0
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SEARCH_QUERY: 'repo:ethereum-optimism/developers type:discussions created:${{ env.last_month }}'

    - name: Create issue
      uses: peter-evans/create-issue-from-file@v4
      with:
        title: Monthly developer question and answer metrics report
        token: ${{ secrets.GITHUB_TOKEN }}
        content-filepath: ./issue_metrics.md
        assignees: sbvegan
